<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>WindowsOptimizer.Uninstaller</RootNamespace>
    <AssemblyName>uninstall</AssemblyName>
    <Version>1.0.0</Version>
    <LangVersion>latest</LangVersion>
    <ApplicationIcon>..\Assets\app.ico</ApplicationIcon>
    <Nullable>disable</Nullable>
    <UseWPF>false</UseWPF>
    <UseWindowsForms>false</UseWindowsForms>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
</Project>
